language: rust
rust:
    - stable
    - beta
    - nightly
script:
    - cargo build --verbose
    - cargo test --verbose --package=yoin-core
    - cargo test --verbose --package=yoin-ipadic
    - cargo test --verbose
