[package]
name = "yoin"
version = "0.1.0"
authors = ["agatan <agatan039@gmail.com>"]

[dependencies]
byteorder = "1.0.0"
encoding = "0.2"
clap = "2.20"

[features]
default = ["ipadic"]
ipadic = []

[[bin]]
name = "yoin"
doc = false
path = "src/bin/yoin.rs"
