[package]
name = "yoin"
version = "0.1.0"
authors = ["agatan <agatan039@gmail.com>"]

[dependencies]
yoin-core = { git = "https://github.com/agatan/yoin-core" }
yoin-ipadic = { git = "https://github.com/agatan/yoin-ipadic"  }
clap = "2.20"
