[package]
name = "yoin"
version = "0.0.1"
authors = ["Naomichi Agata <agatan039@gmail.com>"]
readme = "README.md"
license-file = "LICENSE"
keywords = ["japanese", "analyze", "morphological", "morpheme", "NLP"]
description = """
Yoin is a Japanese morphological analyzer written in pure Rust.
This is under development.
"""

[dependencies]
byteorder = "1.0.0"
encoding = "0.2"
clap = "2.20"

[features]
default = ["ipadic"]
ipadic = []

[[bin]]
name = "yoin"
doc = false
path = "src/bin/yoin.rs"
